spring:
  application:
    name: greeting-service
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
  endpoint:
    env:
      show-values: ALWAYS
greeting-service:
  greeting: "Pronto"
  default-value: "Mondo"
